[package]
name = "openapiv3-extended-2"
version = "6.1.0"
authors = ["Spencer Kohan <spencerkohan@gmail.com"]
edition = "2018"
license = "MIT/Apache-2.0"
keywords = ["openapi", "v3"]
homepage = "https://github.com/spencerkohan/openapiv3"
repository = "https://github.com/spencerkohan/openapiv3"
documentation = "https://docs.rs/openapiv3-extended-2"
description = "This crate provides data structures that represent the OpenAPI v3.0.x specification easily deserializable with serde."

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "openapiv3"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indexmap = { version = "2", features = ["serde"] }
anyhow = "1.0.71"
http = "1.0.0"

[dev-dependencies]
assert_matches = "1.5.0"
pretty_assertions = "1.3.0"
serde_yaml = "0.9.22"

[features]
skip_serializing_defaults = []
v2 = []
